#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Compile OpenFOAM libraries and applications
src/Allwmake $targetType $*

# Compile OpenFOAM libraries and applications
applications/Allwmake $targetType $*


#------------------------------------------------------------------------------
