#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# Compiling solvers 

wmake libso ./porousInterfaceProperties/
wmake libso ./porousTwoPhaseProperties/
wmake libso ./porousImmiscibleIncompressibleTwoPhaseMixture/
wmake all ./porousModels
